CREATE TABLE 'q' (
	'qnum' INT(11) NOT NULL AUTO_INCREMENT,
	'q' VARCHAR(100) NULL DEFAULT NULL,
	'qans1' VARCHAR(50) NULL DEFAULT '1',
	'qans2' VARCHAR(50) NULL DEFAULT '2',
	PRIMARY KEY ('qnum')
)